### ISSUE TITLE
Interpret the HTML in the descriptions

### ISSUE THREAD

**Issue by n-kb** [oekoinstitut/kostenrechner#60]
In order to avoid this:
![screenshot from 2016-05-25 12 10 40](https://cloud.githubusercontent.com/assets/864677/15536487/c1dfdd6e-2271-11e6-8fe1-dcd2ba810c9e.png)

**Comment by n-kb** [comment]
Can you HTML these as well?

![screenshot from 2016-05-26 16 09 36](https://cloud.githubusercontent.com/assets/864677/15577315/4e802d38-235c-11e6-96e4-70756b6c5ae8.png)

**Comment by pirhoo** [comment]
Done
