### ISSUE TITLE
When using "Link to visualization", the app doesn't pass all variables to Vehicle object

### ISSUE THREAD

**Issue by n-kb** [oekoinstitut/kostenrechner#63]
When accessing the app via a "Link to visualization", only some parameters are passed to the Vehicle object: car_type, energy_type, acquisition_year etc. Others, like acquisition_price, are not.

E.g this [local link](http://localhost:3000/#/permalink?vehicles=%5B%7B%22acquisition_year%22:2016,%22holding_time%22:4,%22mileage%22:10000,%22energy_type%22:%22diesel%22,%22car_type%22:%22klein%22,%22charging_option%22:%22Wallbox%20bis%2022kW%22,%22fuel_consumption%22:4.7,%22unternehmenssteuersatz%22:30,%22abschreibungszeitraum%22:6,%22sonder_afa%22:false,%22maintenance_costs_total%22:373,%22maintenance_costs_repairs%22:178.2,%22maintenance_costs_inspection%22:116.4,%22maintenance_costs_tires%22:1078.6,%22traffic%22:%22normaler%20Verkehr%22,%22maintenance_costs_charger%22:0,%22fleet_size%22:1,%22training_option%22:%22keine%20Schulung%22,%22training_costs%22:0,%22electricity_consumption%22:0,%22share_electric%22:55,%22second_charge%22:false,%22reichweite%22:150,%22residual_value_method%22:%22Methode%202%22,%22second_user_holding_time%22:6,%22second_user_yearly_mileage%22:10000,%22max_battery_charges%22:2500,%22energy_source%22:%22strom_mix%22,%22fixed_costs_car_tax%22:105.33,%22fixed_costs_insurance%22:785,%22fixed_costs_check_up%22:94.5,%22fixed_costs_total%22:984.8299999999999,%22praemie%22:true,%22acquisition_price%22:90000,%22inflationsrate%22:1.5,%22_2016_benzin_price%22:1.19,%22_2016_diesel_price%22:1,%22_2016_elec_price%22:0.24,%22evolution_hydrocarbon_price_until_2050%22:2,%22evolution_elec_price_until_2020%22:1.3,%22evolution_elec_price_until_2030%22:-0.27999999999999997,%22evolution_elec_price_until_2050%22:-0.58,%22residual_value_fixed%22:41690,%22charging_option_cost%22:0,%22cash_bonus_amount%22:0,%22discount_rate%22:5%7D,%7B%22acquisition_year%22:2016,%22holding_time%22:4,%22mileage%22:10000,%22energy_type%22:%22BEV%22,%22car_type%22:%22klein%22,%22charging_option%22:%22Wallbox%20bis%2022kW%22,%22fuel_consumption%22:6.46,%22unternehmenssteuersatz%22:30,%22abschreibungszeitraum%22:6,%22sonder_afa%22:false,%22maintenance_costs_total%22:319,%22maintenance_costs_repairs%22:137.76,%22maintenance_costs_inspection%22:109.2,%22maintenance_costs_tires%22:72,%22traffic%22:%22normaler%20Verkehr%22,%22maintenance_costs_charger%22:50,%22fleet_size%22:1,%22training_option%22:%22keine%20Schulung%22,%22training_costs%22:0,%22electricity_consumption%22:14.52,%22share_electric%22:55,%22second_charge%22:false,%22reichweite%22:150,%22residual_value_method%22:%22Methode%202%22,%22second_user_holding_time%22:6,%22second_user_yearly_mileage%22:10000,%22max_battery_charges%22:2500,%22energy_source%22:%22strom_mix%22,%22fixed_costs_car_tax%22:0,%22fixed_costs_insurance%22:721,%22fixed_costs_check_up%22:53.5,%22fixed_costs_total%22:774.5,%22praemie%22:true,%22acquisition_price%22:19066,%22inflationsrate%22:1.5,%22_2016_benzin_price%22:1.19,%22_2016_diesel_price%22:1,%22_2016_elec_price%22:0.24,%22evolution_hydrocarbon_price_until_2050%22:2,%22evolution_elec_price_until_2020%22:1.3,%22evolution_elec_price_until_2030%22:-0.27999999999999997,%22evolution_elec_price_until_2050%22:-0.58,%22residual_value_fixed%22:7725,%22charging_option_cost%22:722,%22cash_bonus_amount%22:4000,%22discount_rate%22:5%7D%5D) should pass on a 90000 value for acquisition_price to the new Vehicle object, but doesn't do so.

**Comment by pirhoo** [comment]
Since I can arbitrary export every property from the vehicule object, only variables listed here are saved:
https://docs.google.com/spreadsheets/d/1-BxTbzc5z-04-0-3Q4KJTJtLKmmjAOE5s8X8bzEdv5Q/edit#gid=0

So you have to give me the exact list of variables that must be present in the permalink.

**Comment by n-kb** [comment]
The variable in question is already in the local link. The problem is that the value's not passed to the Vehicle object when it's created.

**Comment by pirhoo** [comment]
But why are you talking about `acquisition_cost` (which is not in the spreadsheet) ?

**Comment by n-kb** [comment]
Sry it's `acquisition_price`, var n°34
